version: "3.8"
services:
  mongodb:
    build: ./mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-app
    command: 
      - /import.sh
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - mern-app
    restart: always
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  data:
  logs:

