require('dotenv').config()
const express = require('express')
const app = express()
const cors = require('cors')
const connection = require('./db')
const userRoutes = require("./routes/users")
const authRoutes = require("./routes/auth")
const fromRoutes = require("./routes/forms")
const saveFile = require("./routes/saveFile")

//middleware
app.use(express.json())
app.use(cors())
const port = process.env.PORT || 8080
app.listen(port, () => console.log(`Nasłuchiwanie na porcie ${port}`))
connection()
app.use("/api/users", userRoutes)
app.use("/api/auth", authRoutes)
app.use("/api/forms", fromRoutes)
app.use("/api/saveFile", saveFile)
